### ISSUE TITLE
API reference?

### ISSUE THREAD

**Issue by igororlov** [Starefossen/node-rema-ae-api#1]
Hei @Starefossen 
Vet du om det er mulig å eksportere data fra Æ, eventuelt få tilgang til backend API? Takk!

**Comment by Starefossen** [comment]
Det er mulig, men du må observere din applikasjon for å få hentet ut API nøkkel og OAuth token. Jeg benytter [MITM Proxy](https://mitmproxy.org) til dette.

**Comment by igororlov** [comment]
Strålende! Works as a charm :+1: Tusen takk!

**Comment by marcusrong** [comment]
Hei @Starefossen @igororlov. Jeg prøver å hente AOuth token og API key med mitmproxy, men får det ikke til. Virker deres løsninger fortsatt eller gjør jeg noe feil? All hjelp er velkommen :)

**Comment by Starefossen** [comment]
@MarcusOslandRong Æ-appen med tilhørende APIer har vært gjennom mye utvikling over de siste årene. Det er godt mulig at denne metoden ikke lenger fungerer - jeg har ikke testet det i det siste.

**Comment by HelgeSverre** [comment]
Laget en guide for dette for ett par uker siden, skal fortsatt være fungerende:

https://www.reddit.com/r/norge/comments/rv5eoc/comment/isxo2hh/?utm_source=share&utm_medium=web2x&context=3
